name: film_library
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  cached_network_image: ^3.4.0
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/bottom_bar/
    - assets/images/start_page/
    - assets/images/profile/
    - assets/images/posters/
